### ISSUE TITLE
mysp.myprosody(p,c) giving parselmouth.PraatError: Stray text after 'else'. error

### ISSUE THREAD

**Issue by bbrij87** [Shahabks/myprosody#22]
Hello,

I could all functions up to mysp.myprosody(p,c) and this throws an error which is related to PRAAT file. 

parselmouth.PraatError: Stray text after 'else'.
Script line 332 not performed or completed:
« else vowel1=vowel1+0 »
Script not completed.

 mysp.myprosody(p,c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bbrij\AppData\Local\Programs\Python\Python39\lib\site-packages\myprosody\__init__.py", line 369, in myprosody
    objects= run_file(sourcerun, -20, 2, 0.3, "yes",sound,path, 80, 400, 0.01, capture_output=True)
parselmouth.PraatError: Stray text after 'else'.
Script line 332 not performed or completed:
« else vowel1=vowel1+0 »
Script not completed.

I could run previous functions successfully. 
>>> mysp.myspsyl(p,c)
number_ of_syllables= 121
>>> mysp.mysppron(p,c)
Pronunciation_posteriori_probability_score_percentage= :94.97

Here is the screenshot if it helps:
![image](https://user-images.githubusercontent.com/1615879/113972895-119dd600-9859-11eb-853a-49e49de4a499.png)

**Comment by bbrij87** [comment]
Update: I executed the script on remote online server and got different response but I assume issue is with /myprosody/dataset/essen/MLTRNL.praat file. 

![image](https://user-images.githubusercontent.com/1615879/114143999-7842f280-9932-11eb-84f5-584f40b6d8dd.png)

The line 302  in myprosody/myprosody.py doesn't return anything. 
![image](https://user-images.githubusercontent.com/1615879/114144336-d96ac600-9932-11eb-819a-c4cf0ae58017.png)

**Comment by bbrij87** [comment]
Any update?

**Comment by ananas-hebo** [comment]
[MLTRNL.praat.zip](https://github.com/Shahabks/myprosody/files/6440145/MLTRNL.praat.zip)

@bbrij87 

I repaired it.

**Comment by AanchalA** [comment]
@hebo1982 
I replaced the old MLTRNL.praat with this new file and now it is giving a different error.
I tried using with python version 3.9 but since that did not work, I also tried with 3.7, but that also did not solve my problem.

`ERROR:root:Unknown symbol:
« appendInfoLine:0.7733333333333333,tab$,'
Script line 882 not performed or completed:
« appendInfoLine:'avepauseduratin',tab$,'avelongpause',tab$,'speakingtot:2',tab$,'avenumberofwords',tab$,'articulationrate',tab$,'inpro',tab$,'f1norm',tab$,'mr',tab$,'q25',tab$,'q50',tab$,'q75', tab$, 'std',tab$,'fmax',tab$,'fmin',tab$,'vowelinx1',tab$,'vowelinx2',tab$,'formantmean',tab$,'formantstd',tab$,'nuofwrds:0',tab$,'npause',tab$,'ins',tab$,'fillerratio',tab$,'xx',tab$,xxx$,tab$,'totsco',tab$,xxban$,tab$,'speakingrate' »
Script not completed.
Traceback (most recent call last):
  File "/home/ubuntu/Aanchal/EDA-and-Feature-Engineering/prosody/prosody_features.py", line 464, in mysplev
    objects = run_file(sourcerun, -20, 2, 0.3, "yes", sound, path, 80, 400, 0.01, capture_output=True)
parselmouth.PraatError: Unknown symbol:
« appendInfoLine:0.7733333333333333,tab$,'
Script line 882 not performed or completed:
« appendInfoLine:'avepauseduratin',tab$,'avelongpause',tab$,'speakingtot:2',tab$,'avenumberofwords',tab$,'articulationrate',tab$,'inpro',tab$,'f1norm',tab$,'mr',tab$,'q25',tab$,'q50',tab$,'q75', tab$, 'std',tab$,'fmax',tab$,'fmin',tab$,'vowelinx1',tab$,'vowelinx2',tab$,'formantmean',tab$,'formantstd',tab$,'nuofwrds:0',tab$,'npause',tab$,'ins',tab$,'fillerratio',tab$,'xx',tab$,xxx$,tab$,'totsco',tab$,xxban$,tab$,'speakingrate' »
Script not completed.`

**Comment by hebo1982** [comment]
@AanchalA 

Cloud you show code help me reproduce this error?

The error like from praat script. You can debug [praat](https://www.fon.hum.uva.nl/praat/).

**Comment by AanchalA** [comment]
Hey @hebo1982 
This issue was occuring because I was using a smaller file (5 seconds). When I used another file (17 seconds), this error was gone, but the values for all the features was zero.

**Comment by tyriaa** [comment]
> @AanchalA
> 
> Cloud you show code help me reproduce this error?
> 
> The error like from praat script. You can debug [praat](https://www.fon.hum.uva.nl/praat/).



> [MLTRNL.praat.zip](https://github.com/Shahabks/myprosody/files/6440145/MLTRNL.praat.zip)
> 
> @bbrij87
> 
> I repaired it.
> 
> You should replace the file 'myprosody/dataset/essen/MLTRNL.praat'.

Hey how did you fix it ? 

Because that work for me but I have the same issue with mysplev()

**Comment by gabrieltirado** [comment]
> > @AanchalA
> > Cloud you show code help me reproduce this error?
> > The error like from praat script. You can debug [praat](https://www.fon.hum.uva.nl/praat/).
> 
> > [MLTRNL.praat.zip](https://github.com/Shahabks/myprosody/files/6440145/MLTRNL.praat.zip)
> > @bbrij87
> > I repaired it.
> > You should replace the file 'myprosody/dataset/essen/MLTRNL.praat'.
> 
> Hey how did you fix it ?
> 
> Because that work for me but I have the same issue with mysplev()

 name 'pickle' is not defined: https://stackoverflow.com/questions/48477949/not-able-to-pip-install-pickle-in-python-3-6

**Comment by jk6721189** [comment]
> > @AanchalA
> > Cloud you show code help me reproduce this error?
> > The error like from praat script. You can debug [praat](https://www.fon.hum.uva.nl/praat/).
> 
> > [MLTRNL.praat.zip](https://github.com/Shahabks/myprosody/files/6440145/MLTRNL.praat.zip)
> > @bbrij87
> > I repaired it.
> > You should replace the file 'myprosody/dataset/essen/MLTRNL.praat'.
> 
> Hey how did you fix it ?
> 
> Because that work for me but I have the same issue with mysplev()

It worked like charm post replacement of MLTRNL.praat(26.2KB) to MLTRNL.praat(26.1KB). thank you!

**Comment by Kushwho** [comment]
@tyriaa This is because this function has a sklearn.tree.tree dependency and it was removed from scikit-learn version 0.24.
